### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by factyy** [crystal-lang-tools/scry#178]
Tried to use `scry` with `emacs/lsp-mode` and found out that completion is completely broken.

Looking at opened issues makes me wonder if this project is completely abandoned?

**Comment by maxbertinetti** [comment]
@factyy I think you can try https://github.com/elbywan/crystalline

**Comment by factyy** [comment]
Wow! Will try it, thanks!

**Comment by mcorossigo** [comment]
I mean... This doesn't really answer the question / address the issue.
Is crystalline officially suggested as a replacement?

**Comment by maxbertinetti** [comment]
Actually the situation in Crystal Tools is as following: none like working on Tooling since Crystal is not hitting stable release.
@elbywan don't want to put Crystalline on Crystal Tool for now.
None is following development for Scry for what I know.
If you follow the [forum](https://forum.crystal-lang.org/t/poll-which-lsp-analyzer-are-you-using-with-crystal/2803) you can see Ameba is the most used tool, followed by Crystalline.
I'm a sort of maintainer for this organisation now, but I don't have other ppl willing to progress on tooling and so for now I'm doing only little maintenance where I can waiting for a better tomorrow.
