### ISSUE TITLE
Completion: Method db generation should be resilient to invalid files

### ISSUE THREAD

**Issue by laginha87** [crystal-lang-tools/scry#60]
if you have this scenario.

```crystal
# File b.cr
class A
enda
```

```crystal
# File a.cr
require "./b"

File.
```

The completion on File. won't work because b.cr is invalid crystal code.

Note: If you 're trying this out in vscode because dependancies are preloaded, Run Reload the Window after saving the files.

Issue is here: https://github.com/crystal-lang-tools/scry/blob/c48f421418900a370670408566963a01e5fb829b/src/scry/completion/method_db.cr#L27

**Comment by bew** [comment]
Note: make sure to use a specific commit when using a link link to code, otherwise the link may be invalid later, for example:
https://github.com/crystal-lang-tools/scry/blob/c48f421418900a370670408566963a01e5fb829b/src/scry/completion/method_db.cr#L27
(and it will even give you a preview fro free!!)

**Comment by laginha87** [comment]
This was fixed in https://github.com/crystal-lang-tools/scry/pull/62
